### ISSUE TITLE
Mersey Green Map is not loading

### ISSUE THREAD

**Issue by ColmDC** [SolidarityEconomyAssociation/mersey-green-project#5]
The map 
https://maps.coop/mersey-green/
nor is 
https://maps.coop/ica/ 
and https://prod.maps.coop/newbridge-project/

is not loading.

**Comment by wu-lee** [comment]
Investigated - the problem is that prod-1's disk was full (again).

This is I think because of the older versions of the code used in these deployments, some of which don't include the fix for the problem which allows the temp directory to fill up and cause this problem.

Essentially, we need to upgrade them - probably something to do as part of moving them.

**Comment by ColmDC** [comment]
All working again. We can plan upgrades in the new year.
